
  name: hipoteca-dia-semana
  version: '0.1'
  summary: Aplicación que permite calcular cuota hipoteca y calcula el dia de la semana
  description: |
    La aplicación hace dos cosas totalmente distintas: 
    1) Calcula la cuota de un préstamo usando la fórmula francesa--la más común en españa 
    2) Calcula el dia de la semana a partir del año, mes y dia del mes

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    hipoteca-dia-semana:
      after: [desktop-glib-only]
      plugin: gradle
      source: .
      build: |
        export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
        gradle release -x test -x createGitTag
      install: |
        unzip DIST/hipoteca-dia-semana_bin-*.zip -d \
        $SNAPCRAFT_PART_INSTALL/
      build-packages:
        - unzip
        - openjdk-11-jdk
  
